/*******************************************************************************************************************//**
 * Generated by @CSoffiati
 * 05/2025
 * https://github.com/Correx96/RA0E1_LedMatrix
 * This project is open source and available under the MIT License.
 * Parts of this project have been acquired from other authors and modified.
 * All credits to their owners, which are specified in the respective files.
 **********************************************************************************************************************/


#include "hal_data.h"
#include <stdbool.h>
#include "Rotary.h"
#include "ledmatrix57.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

//Timer variables
#define SYSTICK_DIVIDER         1000    //Clock 32Mhz -> Systick 1ms with divider = 1000
#define pinD1_Config        &IOPORT_CFG_CTRL, D1
#define pinD2_Config        &IOPORT_CFG_CTRL, D2
#define SIZE                    94

uint32_t systick_counter;
bool flag_1ms;
bool flag_10ms;
bool flag_100ms;
bool flag_1s;

//Encoder variables
uint32_t pinD1;
uint32_t pinD2;
unsigned char result;

//LedMatrix variables
signed int counter;
signed int oldCounter;
char charactersArray[SIZE];
uint32_t charactersIndex;

//Variables and systick setup
void setup(void)
{
    systick_counter = 0;
    flag_1ms = false;
    flag_10ms = false;
    flag_100ms = false;
    flag_1s = false;

    SysTick_Config(SystemCoreClock/SYSTICK_DIVIDER);

    pinD1 = digitalRead(pinD1_Config);
    pinD2 = digitalRead(pinD2_Config);

    charactersIndex = 0;
    for(int i=0; i < SIZE; i++)
    {
      charactersArray[i] = (char)(i+32);
    }
    ledmatrix_WriteChar(charactersArray[charactersIndex], Font_5x7, White);
}

void SysTick_Handler(void)
{
    systick_counter++;
    flag_1ms = true;

    if (systick_counter % 10 == 0)
        flag_10ms = true;

    if (systick_counter % 100 == 0)
        flag_100ms = true;

    if (systick_counter % 1000 == 0)
        flag_1s = true;
}

void read_encoder_state(void)
{
    if(counter > 1000000000 || counter < -1000000000)
      counter = 0;
    pinD1 = digitalRead(pinD1_Config);
    pinD2 = digitalRead(pinD2_Config);

    result = Rotary_process(pinD1_Config, pinD2_Config);
    if (result == DIR_CW)
        counter++;
    else if (result == DIR_CCW)
        --counter;
}

void update_Character(void)
{
    if(counter > oldCounter)
    {
        charactersIndex = (charactersIndex + 1) % SIZE;
        ledmatrix_WriteChar((char)charactersArray[charactersIndex], Font_5x7, White);
        oldCounter = counter;
    }
    else if(counter < oldCounter)
    {
        charactersIndex = (charactersIndex - 1 + SIZE) % SIZE;
        ledmatrix_WriteChar((char)charactersArray[charactersIndex], Font_5x7, White);
        oldCounter = counter;
    }
}

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    setup();

    while(1)
    {
        ledmatrix_UpdateScreen();

        if (flag_1ms)
        {
            flag_1ms = false;

            //Code to execute every 1ms
            read_encoder_state();
        }

        if (flag_10ms)
        {
            flag_10ms = false;

            //Code to execute every 10ms
            update_Character();
        }

        if (flag_100ms)
        {
            flag_100ms = false;

            //Code to execute every 100ms
        }

        if (flag_1s)
        {
            flag_1s = false;

            //Code to execute every 1s
        }
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0

        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery. Placing the enable here, before clock and
         * C runtime initialization, should negate the need for a delay since the initialization will typically take more than 6us. */
#endif
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

#if BSP_CFG_SDRAM_ENABLED

        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
